# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  RBENV_ROOT:
    sh: echo $HOME/.rbenv
  BUNDLE: "{{.RBENV_ROOT}}/shims/bundle"

tasks:
  default:
    desc: Serve Jekyll site with live reload
    cmds:
      - task: serve

  serve:
    desc: Start Jekyll development server with live reload
    cmds:
      - "{{.BUNDLE}} exec jekyll serve --livereload"

  build:
    desc: Build Jekyll site for production (GitHub Pages)
    cmds:
      - "{{.BUNDLE}} exec jekyll build"

  clean:
    desc: Clean Jekyll build artifacts
    cmds:
      - "{{.BUNDLE}} exec jekyll clean"
      - rm -rf _site

  install:
    desc: Install Jekyll and dependencies
    cmds:
      - "{{.BUNDLE}} install"

  format:
    desc: Format all code files (HTML, SCSS, YAML)
    cmds:
      - npx prettier --write "**/*.{html,scss,yml,yaml,md}" --ignore-path .gitignore
